version: 2
sources:
  - name: shared
    database: "{{('dbt_db')}}"
    schema: staging_layer

    tables:
      - name: stg_customers
      - name: stg_orders
      - name: stg_payments
      - name: stg_products


